Year II/sem 1/Dezvoltarea aplicatiilor web - ASP.NET/Examen/Model_Examen/Model_Examen/Controllers/GiftCardsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model_Examen.Models;

namespace Model_Examen.Controllers
{
    public class GiftCardsController : Controller
    {
        private readonly AppDBContext db = new AppDBContext();


        public IActionResult Index()
        {
            var cards = db.GiftCards.Include("Brand");
            ViewBag.Cards = cards;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            return View();
        }

 
        public IActionResult Show(int id)
        {
            GiftCard card = db.GiftCards.Include("Brand")
                               .Where(c => c.Id == id)
                               .First();

            return View(card);
        }

        public IActionResult New()
        {
            GiftCard card = new GiftCard();

            card.Brands = GetAllBrands();

            return View(card);
        }

        [HttpPost]
        public IActionResult New(GiftCard card)
        {

            if (ModelState.IsValid)
            {   
                if(card.DataExp < DateTime.Now)
                {
                    TempData["message"] = "Data de expirare nu poate fi mai veche decat ziua curenta";
                    ViewBag.message = TempData["message"].ToString();
                    card.Brands = GetAllBrands();
                    return View(card);
                } else {
                    db.GiftCards.Add(card);
                    db.SaveChanges();
                    TempData["message"] = "Cardul a fost adaugat cu succes";
                    return RedirectToAction("Index");
                }
               
            }
            else
            {
                ViewBag.message = null;
                card.Brands = GetAllBrands();
                return View(card);
            }

        }

  
        public IActionResult Edit(int id)
        {

            GiftCard card = db.GiftCards.Include("Brand")
                                        .Where(c => c.Id == id)
                                        .First();

            card.Brands = GetAllBrands();

            return View(card);

        }

      
        [HttpPost]
        public IActionResult Edit(int id, GiftCard requestGiftCard)
        {
            GiftCard card = db.GiftCards.Find(id);
            requestGiftCard.Brands = GetAllBrands();

            if (ModelState.IsValid)
            {
                if (requestGiftCard.DataExp < DateTime.Now)
                {
                    TempData["message"] = "Data de expirare nu poate fi mai veche decat ziua curenta";
                    ViewBag.message = TempData["message"].ToString();
                    card.Brands = GetAllBrands();
                    return View(card);
                }
                else
                {
                    card.Denumire = requestGiftCard.Denumire;
                    card.Descriere = requestGiftCard.Descriere;
                    card.Denumire = requestGiftCard.Denumire;
                    card.DataExp = requestGiftCard.DataExp;
                    card.Procent = requestGiftCard.Procent;
                    card.BrandId = requestGiftCard.BrandId;
                    TempData["message"] = "Cardul a fost modificat";
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.message = null;
                return View(requestGiftCard);
            }
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            GiftCard card = db.GiftCards.Find(id);
            db.GiftCards.Remove(card);
            db.SaveChanges();
            TempData["message"] = "Cardul a fost sters";
            return RedirectToAction("Index");
        }

        public IActionResult Search()
        {
            /* Nr 1
            var cards = db.GiftCards.Include("Brand").OrderByDescending(a => a.DataExp).Where(c => c.DataExp > DateTime.Now && c.DataExp <= DateTime.Now.AddDays(5) && c.Procent >= 30);

            var search = "";

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();

                List<int> cardIds = db.GiftCards.Where
                                        (
                                         c => c.Denumire.Contains(search)
                                        ).Select(c => c.Id).ToList();

                cards = db.GiftCards.Where(card => cardIds.Contains(card.Id))
                                      .Include("Brand")
                                      .OrderByDescending(a => a.DataExp).Where(c => c.DataExp > DateTime.Now && c.DataExp <= DateTime.Now.AddDays(5) && c.Procent >= 30);

            }

            ViewBag.SearchString = search;
            ViewBag.Cards = cards;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }


            return View();
            */
            var cards = db.GiftCards.Include("Brand");

            var search = "";

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();

                List<int> cardIds = db.GiftCards.Where
                                        (
                                         c => c.Procent.ToString().Contains(search)
                                        ).Select(c => c.Id).ToList();

                List<int> brandIds = db.Brands.Where
                                    (
                                        b => b.Nume.Contains(search)
                                    ).Select(b => b.Id).ToList();

                List<int> mergedIds = cardIds.Union(brandIds).ToList();

                cards = db.GiftCards.Where(card => mergedIds.Contains(card.Id))
                                      .Include("Brand");

            }

            ViewBag.SearchString = search;
            ViewBag.Cards = cards;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }


            return View();
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllBrands()
        { 
            var selectList = new List<SelectListItem>();

            var brands = from b in db.Brands
                             select b;

            foreach (var brand in brands)
            { 
                selectList.Add(new SelectListItem
                {
                    Value = brand.Id.ToString(),
                    Text = brand.Nume
                });
            }

            return selectList;
        }
    }
}

Year II/sem 1/Dezvoltarea aplicatiilor web - ASP.NET/Examen/Model_Examen/Model_Examen/Views/Shared/CardInfo.cshtml
<div class="card-body">

    <h3 class="card-title alert-success py-3 px-3 rounded-2">@Model.Denumire</h3>

    <div class="card-text">@Model.Descriere</div>

    <div class="d-flex justify-content-between flex-row mt-5">

        <div><i class="bi bi-globe"></i><b>Brand: </b>@Model.Brand.Nume</div>
        <div class="card-text"><b>Procent: </b>@Model.Procent %</div>
        <div class="card-text"><b>Data expirare: </b>@Model.DataExp</div>

    </div>
    <br />
    <div class="d-flex flex-row justify-content-between">

        <a class="btn btn-success" href="/GiftCards/Edit/@Model.Id">Editeaza card</a>

        <form method="post" action="/GiftCards/Delete/@Model.Id">

            <button class="btn btn-danger" type="submit">Sterge card</button>

        </form>

    </div>

</div>

Year II/sem 1/Dezvoltarea aplicatiilor web - ASP.NET/Examen/Model_Examen/Model_Examen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Denumire"] - Model_Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Model_Examen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Model_Examen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="GiftCards" asp-action="New">Adaugare card</a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="GiftCards" asp-action="Index">Afisare carduri cadou</a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="GiftCards" asp-action="Search">Cautare carduri</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Model_Examen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>